######################################################
###                                                ###
###     _____      _      ____     ____     ____   ###
###    |  ___|    / \    |  _ \   / ___|  / ___|   ###
###    | |_      / □ \   | | | | | |     | |  _    ###
###    |  _|    / ___ \  | |_| | | |___  | |_| |   ###
###    |_|     /_/   \_\ |____/   \____| \____|    ###
###                                                ###
######################################################

##################################################################################################################################################
## Reactions                                                                                                                                    ##
## If you want to suggest a chat reaction type, or need to ask for help, you can do so in our Discord: https://discord.gg/GGCk3zdgQP            ##
## Valid Types (as of 1.0): [UNSCRAMBLE, TYPE, SOLVE, REVERSE, FINISH_PHRASE]                                                                   ##
##                                                                                                                                              ##
## Rewards                                                                                                                                      ##
## These are the possible rewards a player can get for winning a chat reaction                                                                  ##
## If you want to randomly set what reward the player gets (which then uses the chance value), set the 'reward' key in the reaction to 'random' ##
## Otherwise, set it to the key of the reward, for example 'one_diamond' or 'eight_oak_logs'                                                    ##
##################################################################################################################################################

# Changes to this value could result in the plugin not loading or your config being corrupted.
version: 1.0

options:
  case-sensitive-answers: true
  interval: 300000
  timeout: 60000
  min-players: 2
  disabled-chat-reactions: []

